### ISSUE TITLE
Because you locked the thread... Random input

### ISSUE THREAD

**Issue by BluePlastics** [atar-axis/xpadneo#130]
No I'm not 12, I just really don't have time in my life to deal with the "pass the buck" mentality I dealt with working in the casino industry, years of vendors saying "that's not my problem",  years of telling their higher ups that they said "its not their problem" and  years of it getting fixed 5 minutes after getting off of the phone with their supervisor.

Cheers!

**Comment by atar-axis** [comment]
I understand that you feel like back to those times but open-source projects like this are a bit different in my eyes, it is at first up to the users to investigate a problem thoroughly and help actively fixing the problem. This includes reading the documentation and providing all the debug logs in question (how is explained at the docs too).

**Expect what you paid for...** 

Anyway, in your case I am like 99% sure that the problem is not the driver but something different like sdl, another driver or the emulator mapping,... But a closed issue can be reopened if you are convincing on that the problem is in fact caused by xpadneo.

Regards, Flo
