### ISSUE TITLE
Is it possible to support to build as an android kernel module

### ISSUE THREAD

**Issue by v-gu** [atar-axis/xpadneo#394]
Just wandering, thank you everyone that could leave a comment.

**Comment by kakra** [comment]
In theory, it's perfectly possible. But you need the kernel headers and a proper tool chain for compiling the module. Also, you may need features that are not shipped by the stock Android kernel. Building for Android is probably very similar to building for Raspberry Pi.

If you compile the module without the stock kernel headers/sources, you may not be able to load the module due to security restrictions. This would be completely out of scope of this project. Module signing is part of the distribution which is Android or one of its community forks in this case.

Also, to load the module at all, you'd need a jail-broken Android to gain root permissions. Please respect to not ask about jail-breaks here or in our community unless unlocking the boot loader of your device is officially supported by the manufacturer (which then probably allows to easily gain root access).

**Comment by v-gu** [comment]
I tried on my phone(it's my own discretion), the build was success, and the kernel was replaced successfully too. After BT connect, the controller rumble just as on Linux. But it seems the Android system didn't pickup the device with rumble support, apps can't recognize the device's rumble feature.

**Comment by kakra** [comment]
I'm not sure if Android apps are even supposed to support rumble. It could make sense to look up the SDK documentation to see how it is supposed to work, then look at the AOSP to see how it's actually implemented. Android may filter rumble support by actual device IDs or device strings.

**Comment by KayJay7** [comment]
> I tried on my phone(it's my own discretion), the build was success, and the kernel was replaced successfully too. After BT connect, the controller rumble just as on Linux. But it seems the Android system didn't pickup the device with rumble support, apps can't recognize the device's rumble feature.

@v-gu How did you built it on your phone? AFAIK there is no dkms on android and I can't get my computer to cross compile it for arm.

Regarding the rumble features, android applications usually do not use the interfaces exposed by this driver directly. But I'm interested in trying if something like sdl and moonlight can pick it up.

**Comment by kakra** [comment]
> if something like sdl

It can if the system allows direct write access to the hidraw device. This is probably not allowed in Android. OTOH, SDL supports rumble through the input API, too, but the Android kernels are probably to old for hid-microsoft to support rumble via input API, or hid-microsoft even supporting the device (and then it's handled by hid-generic which doesn't support rumble).

I'd still not recommend trying xpadneo on Android for general usage because the button mapping differs and the system APIs and/or apps may not expect that.

**Comment by KayJay7** [comment]
AFAICT, Android allows accessing hidraw if selinux is set to permissive, which on some (probably all) devices requires root access, but so would dkms, so it's nothing new. For the mappings, there's apps that take care of that. I don't think it should be recommended, but on older android devices it might be the only way to use rumble via Bluetooth.

**Comment by kakra** [comment]
Closing because support on Android it out of scope of this project.

**Comment by carpetoctopus** [comment]
Hello, I am aware this is an old question, but I managed to successfully build an Android kernel with the xpadneo module included. Everything works, even mouse emulation. I wrote about it [here](https://xdaforums.com/t/guide-unofficial-xbox-wireless-controller-rumble-support.4787838) in case someone is interested.

**Comment by kakra** [comment]
> Hello, I am aware this is an old question, but I managed to successfully build an Android kernel with the xpadneo module included. Everything works, even mouse emulation. I wrote about it [here](https://xdaforums.com/t/guide-unofficial-xbox-wireless-controller-rumble-support.4787838) in case someone is interested.

@carpetoctopus Cool success story, really nice. I am happy that even mouse mode works and seems useful.

Here's something that may be interesting:
https://github.com/kakra/linux/pull/38

It tracks kernel patches to directly integrate xpadneo without conflicting hid-microsoft. It is still based on an older kernel and older xpadneo version. Expect an update soon. If you subscribe the PR, you will get a notification when I updated the patches.

Additionally, we will soon release a python utility to automatically create a kernel patch from every future xpadneo version perfectly matching your kernel sources in any version, so you won't depend on my patch tracker.

If you use mouse mode, feel free to join our Discord and report, how it feels and works. It's still experimental and I put some effort into making the cursor movement feel natural (it's much more difficult than one may think because you need error diffusion). But I'm still not sure about movement speed etc. Also, which is expecially important for battery-powered devices: xpadneo currently enables a fixed 100 hz timer, even if mouse mode is inactive, meaning it will wake up the CPU 100 times per seconds. A future version will change this and will automatically switch the timer on and off, first improvement: while mouse mode is on, second improvement: while mouse mode is on and there's actual cursor movement.

So stay tuned. Thanks. :-)
