### ISSUE TITLE
Screen Auto-Sleep Issue with Windows Games on Wine, Lutris, and Similar Software

### ISSUE THREAD

**Issue by RaulKong898** [atar-axis/xpadneo#500]
I'm not sure if this is a bug or should be a feature request. When playing Windows games, like through Wine or other emulation programs that only run the game, the screen should stay on, just like it does when playing with a controller on Steam. On Steam, the screen doesn’t go black, nor does it turn off, which makes gameplay smoother, especially in online games. However, with games run through Wine, Lutris, Bottles, or similar programs, the screen turns off and makes it harder to play, causing us to lose more quickly.

I would like this to be fixed so that Windows games, emulated through these programs, don’t trigger automatic screen shutdown. Additionally, I would like to see an update that improves the xpadneo driver for controllers. I'm not sure if this is a bug or a suggestion, but I'm reporting it as a bug since the game is still active, but it's treated as inactivity, even though I'm playing with a controller, which shouldn't be the case.

**Comment by kakra** [comment]
You should run wine or launchers like Lutris through `systemd-inhibit` which can be used to inhibit the screen saver or sleeping. This is and cannot be the job of xpadneo. xpadneo doesn't know if a game or app connected to the device.

I'm not sure how Windows handles that but usually, wine in its core should probably inhibit the screen saver while a fullscreen window is active. Steam handles this automatically meanwhile by inhibiting the screensaver while a game is running. Bottles, Lutris etc should probably do the same. Feature requests should go to those projects.

Closing because we cannot solve this in xpadneo.
